theme: jekyll-theme-merlot
show_downloads: "true"
google_analytics: UA-1860703-9
github:
  zip_url: https://github.com/RintarouTW/CleanRoom/zipball/release
  another_url: https://github.com/RintarouTW/CleanRoom/tarball/release
